version: '3.8'

services:
  app:
    image: 'agile-ecommerce-test:latest'
    build:
      context: .
    container_name: app
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8080:8080"

  db:
    image: postgres
    container_name: db
    env_file:
      - .env
    ports:
      - "5433:5432"